# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1254, 845)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(13, 13, 1231, 591))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLabel = QtWidgets.QLabel(self.groupBox)
        self.leftLabel.setText("")
        self.leftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.leftLabel.setObjectName("leftLabel")
        self.horizontalLayout.addWidget(self.leftLabel)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.rightLabel = QtWidgets.QLabel(self.groupBox)
        self.rightLabel.setText("")
        self.rightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rightLabel.setObjectName("rightLabel")
        self.horizontalLayout.addWidget(self.rightLabel)
        self.startcoordinate_3 = QtWidgets.QLabel(Form)
        self.startcoordinate_3.setGeometry(QtCore.QRect(510, 680, 160, 52))
        self.startcoordinate_3.setStyleSheet("font: 25 24pt \"微软雅黑 Light\";")
        self.startcoordinate_3.setObjectName("startcoordinate_3")
        self.startcoordinate_2 = QtWidgets.QLabel(Form)
        self.startcoordinate_2.setGeometry(QtCore.QRect(512, 612, 160, 52))
        self.startcoordinate_2.setStyleSheet("font: 25 24pt \"微软雅黑 Light\";")
        self.startcoordinate_2.setObjectName("startcoordinate_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(12, 622, 421, 113))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.startcoordinate = QtWidgets.QLabel(self.groupBox_2)
        self.startcoordinate.setGeometry(QtCore.QRect(13, 13, 60, 20))
        self.startcoordinate.setStyleSheet("font: 25 9pt \"微软雅黑 Light\";")
        self.startcoordinate.setObjectName("startcoordinate")
        self.startXY = QtWidgets.QLabel(self.groupBox_2)
        self.startXY.setGeometry(QtCore.QRect(80, 13, 241, 16))
        self.startXY.setObjectName("startXY")
        self.endcoordinate = QtWidgets.QLabel(self.groupBox_2)
        self.endcoordinate.setGeometry(QtCore.QRect(13, 45, 60, 20))
        self.endcoordinate.setStyleSheet("font: 25 9pt \"微软雅黑 Light\";")
        self.endcoordinate.setObjectName("endcoordinate")
        self.endXY = QtWidgets.QLabel(self.groupBox_2)
        self.endXY.setGeometry(QtCore.QRect(80, 45, 241, 16))
        self.endXY.setObjectName("endXY")
        self.nowXY = QtWidgets.QLabel(self.groupBox_2)
        self.nowXY.setGeometry(QtCore.QRect(80, 80, 241, 20))
        self.nowXY.setObjectName("nowXY")
        self.nowcoordinate = QtWidgets.QLabel(self.groupBox_2)
        self.nowcoordinate.setGeometry(QtCore.QRect(13, 77, 60, 20))
        self.nowcoordinate.setStyleSheet("font: 25 9pt \"微软雅黑 Light\";")
        self.nowcoordinate.setObjectName("nowcoordinate")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "挖掘机"))
        self.startcoordinate_3.setText(_translate("Form", "GPS信号"))
        self.startcoordinate_2.setText(_translate("Form", "边界提示"))
        self.startcoordinate.setText(_translate("Form", "起点坐标"))
        self.startXY.setText(_translate("Form", " "))
        self.endcoordinate.setText(_translate("Form", "终点坐标"))
        self.endXY.setText(_translate("Form", " "))
        self.nowXY.setText(_translate("Form", " "))
        self.nowcoordinate.setText(_translate("Form", "当前坐标"))
